### ISSUE TITLE
External Playback (sample export / read)

### ISSUE THREAD

**Issue by cuckydev** [sonicretro/SKC-SMPSOUT#2]
The biggest issue with SMPSPlay currently is that it's embedded with Windows only playback methods, there should be a method to compile without these and to just have a simple function to read X amount of samples in whatever format into a buffer.

**Comment by ValleyBell** [comment]
Well... it's a Windows DLL, of course it has "Windows only playback methods".
It also using lots of Windows-specific stuff for loading resources.

If you want to integrate it with your custom audio playback methods, how would the API look?
It's definitely not just "read samples into buffer", as you'd also need to somehow configure the sample rate / sample format / etc.

**Comment by cuckydev** [comment]
well then I went to the wrong repo, sorry, but in terms of how the API would look, the primary features needed would be initialization to a given format, reading a song from memory, and reading samples

**Comment by Clownacy** [comment]
I imagine the API would be something like the ones used by [libxmp-lite](https://github.com/Clownacy/clownaudio/blob/master/clownaudio/decoders/libxmp-lite.c), [libopenmpt](https://github.com/Clownacy/clownaudio/blob/master/clownaudio/decoders/libopenmpt.c), or [PxTone](https://github.com/Clownacy/clownaudio/blob/master/clownaudio/decoders/pxtone.cpp).
